"""classificacao indicativa e formato da sessao

Revision ID: 6fd13c6b3591
Revises: dd300309fa41
Create Date: 2026-08-22 15:09:46.687943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd13c6b3591'
down_revision: Union[str, Sequence[str], None] = 'dd300309fa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # O autogenerate nao emite o CREATE TYPE ao adicionar coluna de enum numa
    # tabela que ja existe — so ao criar a tabela. Sem isto, o ALTER TABLE
    # falha dizendo que o tipo nao existe.
    audio = sa.Enum("DUBBED", "SUBTITLED", "NATIONAL", name="audio_type")
    formato = sa.Enum("TWO_D", "THREE_D", name="screen_format")
    audio.create(op.get_bind(), checkfirst=True)
    formato.create(op.get_bind(), checkfirst=True)

    op.add_column("sessions", sa.Column("movie_age_rating", sa.String(length=6), nullable=True))

    # As sessoes que ja existem precisam de um valor. Adicionar a coluna com
    # server_default resolve as linhas antigas; remover o default logo em
    # seguida faz com que toda sessao nova seja obrigada a declarar o que e,
    # em vez de herdar silenciosamente um padrao do banco.
    op.add_column(
        "sessions",
        sa.Column(
            "audio",
            audio,
            nullable=False,
            server_default="SUBTITLED",
        ),
    )
    op.add_column(
        "sessions",
        sa.Column(
            "screen_format",
            formato,
            nullable=False,
            server_default="TWO_D",
        ),
    )
    op.alter_column("sessions", "audio", server_default=None)
    op.alter_column("sessions", "screen_format", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "screen_format")
    op.drop_column("sessions", "audio")
    op.drop_column("sessions", "movie_age_rating")

    # O tipo sobrevive a remocao da coluna e impediria o upgrade de rodar de novo.
    sa.Enum(name="screen_format").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="audio_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
