"""corredores entre blocos de poltronas

Revision ID: 8fab6c7372a6
Revises: 6fd13c6b3591
Create Date: 2026-08-22 17:46:35.994590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fab6c7372a6'
down_revision: Union[str, Sequence[str], None] = '6fd13c6b3591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sectors",
        sa.Column(
            "aisles",
            postgresql.ARRAY(sa.Integer()),
            nullable=False,
            server_default="{}",
        ),
    )
    # Setores existentes ficam sem corredor; novos precisam declarar.
    op.alter_column("sectors", "aisles", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sectors', 'aisles')
    # ### end Alembic commands ###
