"""cria salas, setores e sessoes

Revision ID: 9fa72e6bc842
Revises: d883b670fdcb
Create Date: 2026-08-20 19:07:36.708031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa72e6bc842'
down_revision: Union[str, Sequence[str], None] = 'd883b670fdcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizer_id', 'name', name='uq_room_organizador_nome')
    )
    op.create_index(op.f('ix_rooms_organizer_id'), 'rooms', ['organizer_id'], unique=False)
    op.create_table('sectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('seats_per_row', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('rows > 0 AND rows <= 26', name='ck_setor_fileiras'),
    sa.CheckConstraint('seats_per_row > 0 AND seats_per_row <= 40', name='ck_setor_poltronas'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'name', name='uq_setor_sala_nome')
    )
    op.create_index(op.f('ix_sectors_room_id'), 'sectors', ['room_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizer_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_id', sa.String(length=40), nullable=False),
    sa.Column('movie_title', sa.String(length=255), nullable=False),
    sa.Column('movie_overview', sa.Text(), nullable=True),
    sa.Column('movie_poster_url', sa.String(length=500), nullable=True),
    sa.Column('movie_backdrop_url', sa.String(length=500), nullable=True),
    sa.Column('movie_runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('movie_year', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', name='session_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'starts_at', name='uq_sessao_sala_horario')
    )
    op.create_index(op.f('ix_sessions_catalog_id'), 'sessions', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_sessions_organizer_id'), 'sessions', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_sessions_room_id'), 'sessions', ['room_id'], unique=False)
    op.create_index(op.f('ix_sessions_starts_at'), 'sessions', ['starts_at'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('session_sector_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint('price_cents >= 0', name='ck_preco_nao_negativo'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sector_id', name='uq_preco_sessao_setor')
    )
    op.create_index(op.f('ix_session_sector_prices_session_id'), 'session_sector_prices', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_sector_prices_session_id'), table_name='session_sector_prices')
    op.drop_table('session_sector_prices')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_starts_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_room_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_organizer_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_catalog_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_sectors_room_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_rooms_organizer_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
