"""marca poltronas acessiveis

Revision ID: ec63bcc98617
Revises: 9fa72e6bc842
Create Date: 2026-08-20 19:55:56.747218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec63bcc98617'
down_revision: Union[str, Sequence[str], None] = '9fa72e6bc842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_attributes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('seat_code', sa.String(length=4), nullable=False),
    sa.Column('kind', sa.Enum('WHEELCHAIR', 'COMPANION', 'OBESE', 'REDUCED_MOBILITY', name='seat_kind'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'seat_code', name='uq_assento_setor_codigo')
    )
    op.create_index(op.f('ix_seat_attributes_sector_id'), 'seat_attributes', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_attributes_sector_id'), table_name='seat_attributes')
    op.drop_table('seat_attributes')
    # ### end Alembic commands ###
